## Matrix Addition and Mutliplication.

Inputting the dimension of the arrays

In [12]:
import numpy as np
x, y = map(int, input("Enter the dimension of the array: ").split())

Enter the dimension of the array: 3 3


Inputting the arrays

In [7]:
print("Enter the elements of the array: ")
for i in range(x):
    for j in range(y):
        k, l = map(int, input().split())
        array1[i][j] += k
        array2[j][i] += l
print("array1\n: ", array1)
print("array2\n", array2)

Enter the elements of the array: 
1 1
2 2
3 3 
4 4
5 5
6 6
7 7 
8 8 
9 9
array1:  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
array2 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


Arrays for Matrix Multiplication

In [ ]:
array1 = np.zeros((x, y))
array2 = np.zeros((y, x))
ans_array = np.zeros((x, x))

Logic For Matrix Multiplication

In [18]:
for i in range(x):
    for j in range(x):
        for k in range(y):
            ans_array[i][j] += array1[i][k] * array2[k][j]
print("answer\n", ans_array)

Enter the dimension of the array: 2 3
2 3
Enter the elements of the array: 
1 2
2 4
3 6
4 8
5 10
6 12
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 2.  8.]
 [ 4. 10.]
 [ 6. 12.]]
[[ 28.  64.]
 [ 64. 154.]]


LogicFor Array addition

In [14]:
k = 0
for i in range(x):
    for j in range(y):
        ans_array[i][j] += array1[i][j] + array2[i][j]
        k += array1[i][j]
print("answer\n", ans_array)
print("Sum of elements of the 1st matrix\n", k)

answer
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Sum of elements of the 1st matrix
 0.0


Arrays for Matrix Addition

In [13]:
array1 = np.zeros((x,y))
array2 = np.zeros((x,y))
ans_array = np.zeros((x,y))